name: unlock_detector
description: "A Flutter Package to detect if app running while phone is locked or not."
version: 1.0.0
repository: https://github.com/mustafa-707/unlock_detector
issue_tracker: https://github.com/mustafa-707/unlock_detector/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: com.example.unlock_detector
        pluginClass: UnlockDetectorPlugin
      ios:
        pluginClass: UnlockDetectorPlugin
